import type { Provider, DashboardStats } from "./types"

export const mockProviders: Provider[] = [
  {
    id: "1",
    name: "Hospital São Lucas",
    corporateName: "Hospital São Lucas Ltda",
    location: {
      address: "Rua das Flores, 123",
      city: "São Paulo",
      state: "SP",
      neighborhood: "Vila Madalena",
      coordinates: { lat: -23.5505, lng: -46.6333 },
    },
    specialties: ["Cardiologia", "Neurologia", "Oncologia"],
    complexity: ["Alta Complexidade"],
    differentials: ["Atende +11 anos", "Centro de Referência em Oncologia"],
    type: "hospital",
    status: "active",
    averageAppointmentTime: 15,
    averageProcedureTime: 7,
    isStrategicPartner: true,
    contractStartDate: "2020-01-15",
    lastUpdate: "2024-01-15",
    phone: "(11) 3456-7890",
    email: "contato@saolucas.com.br",
  },
  {
    id: "2",
    name: "Clínica Vida Saudável",
    corporateName: "Vida Saudável Medicina Ltda",
    location: {
      address: "Av. Paulista, 1000",
      city: "São Paulo",
      state: "SP",
      neighborhood: "Bela Vista",
      coordinates: { lat: -23.5618, lng: -46.6565 },
    },
    specialties: ["Clínica Geral", "Pediatria", "Ginecologia"],
    complexity: ["Baixa Complexidade"],
    differentials: ["Atendimento 24h", "Telemedicina"],
    type: "clinic",
    status: "active",
    averageAppointmentTime: 5,
    averageProcedureTime: 2,
    isStrategicPartner: false,
    contractStartDate: "2021-03-10",
    lastUpdate: "2024-01-10",
    phone: "(11) 2345-6789",
    email: "contato@vidasaudavel.com.br",
  },
  {
    id: "3",
    name: "Laboratório Exames Plus",
    corporateName: "Exames Plus Diagnósticos S.A.",
    location: {
      address: "Rua Augusta, 500",
      city: "São Paulo",
      state: "SP",
      neighborhood: "Consolação",
      coordinates: { lat: -23.5489, lng: -46.6388 },
    },
    specialties: ["Análises Clínicas", "Imagem", "Patologia"],
    complexity: ["Média Complexidade"],
    differentials: ["Coleta Domiciliar", "Resultados Online"],
    type: "laboratory",
    status: "under_review",
    averageAppointmentTime: 3,
    averageProcedureTime: 1,
    isStrategicPartner: false,
    contractStartDate: "2023-06-01",
    lastUpdate: "2024-01-05",
    phone: "(11) 1234-5678",
    email: "contato@examesplus.com.br",
  },
  {
    id: "4",
    name: "Centro Médico Esperança",
    corporateName: "Centro Médico Esperança Ltda",
    location: {
      address: "Rua da Esperança, 789",
      city: "Rio de Janeiro",
      state: "RJ",
      neighborhood: "Copacabana",
      coordinates: { lat: -22.9068, lng: -43.1729 },
    },
    specialties: ["Ortopedia", "Fisioterapia", "Reumatologia"],
    complexity: ["Média Complexidade"],
    differentials: ["Centro de Reabilitação", "Hidroterapia"],
    type: "clinic",
    status: "active",
    averageAppointmentTime: 10,
    averageProcedureTime: 5,
    isStrategicPartner: true,
    contractStartDate: "2019-08-20",
    lastUpdate: "2024-01-12",
    phone: "(21) 3456-7890",
    email: "contato@esperanca.com.br",
  },
  {
    id: "5",
    name: "Hospital Regional Norte",
    corporateName: "Hospital Regional Norte S.A.",
    location: {
      address: "Av. Norte, 1500",
      city: "Belo Horizonte",
      state: "MG",
      neighborhood: "Centro",
      coordinates: { lat: -19.9167, lng: -43.9345 },
    },
    specialties: ["Emergência", "UTI", "Cirurgia Geral"],
    complexity: ["Alta Complexidade"],
    differentials: ["Pronto Socorro 24h", "UTI Neonatal"],
    type: "hospital",
    status: "contract_ended",
    averageAppointmentTime: 20,
    averageProcedureTime: 10,
    isStrategicPartner: false,
    contractStartDate: "2018-01-01",
    lastUpdate: "2023-12-31",
    phone: "(31) 2345-6789",
    email: "contato@regionalnorte.com.br",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalProviders: 5,
  activeProviders: 3,
  strategicPartners: 2,
  underReview: 1,
  averageAppointmentTime: 10.6,
  coverageByRegion: [
    { region: "São Paulo - SP", count: 3 },
    { region: "Rio de Janeiro - RJ", count: 1 },
    { region: "Belo Horizonte - MG", count: 1 },
  ],
  providersBySpecialty: [
    { specialty: "Cardiologia", count: 1 },
    { specialty: "Clínica Geral", count: 1 },
    { specialty: "Análises Clínicas", count: 1 },
    { specialty: "Ortopedia", count: 1 },
    { specialty: "Emergência", count: 1 },
  ],
  statusDistribution: [
    { status: "Ativo", count: 3, color: "#10b981" },
    { status: "Em Análise", count: 1, color: "#f59e0b" },
    { status: "Contrato Encerrado", count: 1, color: "#dc2626" },
  ],
}
